name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Composer install (for indexing of vendor blade classes)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev
      - name: Clean build
        run: rm -r .git
      - name: Clear config cache
        run: php artisan config:clear
      - name: Generate route cache
        run: php artisan route:cache
      - run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > public/version.json'
        shell: bash
      - name: Make ./storage group writable for, code_owner != run_user
        run: chmod 775 ./storage
      - name: Create tar
        run: tar -czf dtapi_${{ env.RELEASE_VERSION }}.tar.gz ./app ./bootstrap ./config ./database ./lang ./public ./resources ./routes ./storage ./vendor ./composer.json
      - name: Upload release tar
        uses: actions/upload-artifact@v3
        with:
          name: dtapi_${{ env.RELEASE_VERSION }}
          path: dtapi_${{ env.RELEASE_VERSION }}.tar.gz
